export const mockServers = [
    {
        id: '1',
        name: 'Discord Clone Devs',
        initials: 'DC',
        color: 'bg-indigo-500',
        bannerUrl: 'https://picsum.photos/seed/dc/400/120',
        iconUrl: undefined,
        boostLevel: 3,
    },
    {
        id: '2',
        name: 'LiveKit Labs',
        initials: 'LL',
        color: 'bg-purple-500',
        bannerUrl: undefined,
        iconUrl: undefined,
    },
    {
        id: '3',
        name: 'Frontend Guild',
        initials: 'FG',
        color: 'bg-green-500',
        bannerUrl: 'https://picsum.photos/seed/fg/400/120',
        iconUrl: undefined,
        boostLevel: 1,
    },
    {
        id: '4',
        name: 'Design System',
        initials: 'DS',
        color: 'bg-orange-500',
        bannerUrl: undefined,
        iconUrl: undefined,
    },
];
export const mockChannels = {
    '1': {
        categories: [
            {
                id: 'info',
                name: 'Thông tin',
                channels: [
                    { id: 'rules', name: 'rules', type: 'text', unread: 0 },
                    { id: 'announce', name: 'announcements', type: 'text', unread: 3 },
                ],
            },
            {
                id: 'text',
                name: 'Kênh Chat',
                channels: [
                    { id: 'general', name: 'general', type: 'text', unread: 0 },
                    { id: 'random', name: 'random', type: 'text', unread: 12 },
                    { id: 'dev', name: 'dev-talk', type: 'text', unread: 0 },
                    { id: 'music', name: 'music', type: 'text', unread: 0 },
                ],
            },
            {
                id: 'voice',
                name: 'Kênh Thoại',
                channels: [
                    {
                        id: 'vc1',
                        name: 'delta-force-1',
                        type: 'voice',
                        unread: 0,
                        isLive: true,
                        liveLabel: 'Chia Se Man Hinh',
                        activeMembers: [
                            { id: '1', name: 'alice', initials: 'A', color: 'bg-orange-500' },
                            { id: '2', name: 'bob', initials: 'B', color: 'bg-purple-500' },
                            { id: '3', name: 'charlie', initials: 'C', color: 'bg-green-500' },
                        ],
                    },
                    {
                        id: 'vc2',
                        name: 'Dog Guang T3, Trust Me',
                        type: 'voice',
                        unread: 0,
                        isLive: false,
                        liveLabel: '8:41:48',
                        activeMembers: [
                            { id: '4', name: 'diana', initials: 'D', color: 'bg-yellow-500' },
                        ],
                    },
                    { id: 'vc3', name: 'Gaming', type: 'voice', unread: 0 },
                ],
            },
        ],
    },
};
export const mockMembers = [
    {
        id: '1',
        name: 'zutomayo',
        initials: 'Z',
        color: 'bg-purple-500',
        status: 'online',
        role: 'Admin',
    },
    {
        id: '2',
        name: 'alice',
        initials: 'A',
        color: 'bg-orange-500',
        status: 'online',
        role: 'Member',
    },
    {
        id: '3',
        name: 'bob',
        initials: 'B',
        color: 'bg-green-500',
        status: 'idle',
        role: 'Member',
    },
    {
        id: '4',
        name: 'charlie',
        initials: 'C',
        color: 'bg-red-500',
        status: 'dnd',
        role: 'Member',
    },
    {
        id: '5',
        name: 'diana',
        initials: 'D',
        color: 'bg-blue-500',
        status: 'offline',
        role: 'Member',
    },
    {
        id: '6',
        name: 'evan',
        initials: 'E',
        color: 'bg-yellow-500',
        status: 'offline',
        role: 'Member',
    },
];
export const mockMessages = {
    general: [
        {
            id: '1',
            authorId: '2',
            author: 'alice',
            authorColor: 'text-orange-300',
            avatarColor: 'bg-orange-500',
            avatarInitials: 'A',
            content: 'Welcome to the **Discord clone**! Join #general and say :tada:',
            timestamp: '10:01',
            date: 'Today',
            reactions: [
                { emoji: '🔥', count: 4, hasReacted: true, userIds: ['1', '2', '3', '4'] },
                { emoji: '👍', count: 2, hasReacted: false, userIds: ['2', '5'] },
            ],
        },
        {
            id: '2',
            authorId: '1',
            author: 'zutomayo',
            authorColor: 'text-violet-300',
            avatarColor: 'bg-purple-500',
            avatarInitials: 'Z',
            content: 'We are wiring LiveKit next. Check https://livekit.io docs.',
            timestamp: '10:02',
            date: 'Today',
            attachments: [
                {
                    id: 'att-1',
                    type: 'image',
                    url: 'https://picsum.photos/seed/mock-image-1/640/360',
                    filename: 'architecture-board.png',
                    filesize: 182301,
                    width: 640,
                    height: 360,
                    mimeType: 'image/png',
                },
            ],
            replyTo: {
                messageId: '1',
                authorName: 'alice',
                authorColor: 'bg-orange-500',
                content: 'Welcome to the Discord clone!',
            },
        },
        {
            id: '3',
            authorId: '3',
            author: 'bob',
            authorColor: 'text-green-300',
            avatarColor: 'bg-green-500',
            avatarInitials: 'B',
            content: 'Tailwind dark mode looks ~~great~~ *clean* now.',
            timestamp: '10:05',
            date: 'Today',
            editedAt: '10:06',
        },
        {
            id: '4',
            authorId: '2',
            author: 'alice',
            authorColor: 'text-orange-300',
            avatarColor: 'bg-orange-500',
            avatarInitials: 'A',
            content: 'Anyone tried the new components? ping @zutomayo',
            timestamp: '10:07',
            date: 'Today',
            embeds: [
                {
                    url: 'https://tailwindcss.com',
                    title: 'Tailwind CSS',
                    description: 'Rapidly build modern websites without ever leaving your HTML.',
                    siteName: 'tailwindcss.com',
                    color: '#38bdf8',
                },
            ],
        },
        {
            id: '5',
            authorId: '2',
            author: 'alice',
            authorColor: 'text-orange-300',
            avatarColor: 'bg-orange-500',
            avatarInitials: 'A',
            content: 'The sidebar resize is so smooth! Use `PanelGroup` + `Panel`.',
            timestamp: '10:08',
            date: 'Today',
            replyTo: {
                messageId: '2',
                authorName: 'zutomayo',
                authorColor: 'bg-purple-500',
                content: '',
                hasAttachment: true,
            },
        },
    ],
    random: [
        {
            id: '1',
            authorId: '3',
            author: 'bob',
            authorColor: 'text-green-300',
            avatarColor: 'bg-green-500',
            avatarInitials: 'B',
            content: "What's everyone playing lately?",
            timestamp: '09:00',
            date: 'Today',
        },
        {
            id: '2',
            authorId: '4',
            author: 'charlie',
            authorColor: 'text-rose-300',
            avatarColor: 'bg-red-500',
            avatarInitials: 'C',
            content: 'Hollow Knight is amazing.',
            timestamp: '09:15',
            date: 'Today',
        },
    ],
};
//# sourceMappingURL=mock-data.js.map