import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Bell, Hash, HelpCircle, Pin, Search, UserPlus, Users, Volume2, } from 'lucide-react';
import { Separator, Tooltip, TooltipContent, TooltipTrigger } from '@goportal/ui';
export const ChannelHeader = ({ channel, topic = 'Channel topic', showMembers = false, onToggleMembers, }) => {
    if (!channel) {
        return (_jsx("header", { className: "h-12 border-b border-border px-4 flex items-center justify-between text-sm bg-background", children: _jsx("span", { className: "text-muted-foreground", children: "No channel selected" }) }));
    }
    return (_jsxs("header", { className: "h-12 border-b border-border px-4 flex items-center justify-between bg-background", children: [_jsxs("div", { className: "flex items-center min-w-0", children: [channel.type === 'TEXT' ? (_jsx(Hash, { className: "w-5 h-5 text-muted-foreground mr-2" })) : (_jsx(Volume2, { className: "w-5 h-5 text-muted-foreground mr-2" })), _jsx("span", { className: "font-semibold text-base text-foreground truncate", children: channel.name }), _jsx(Separator, { orientation: "vertical", className: "mx-2 h-5" }), _jsx("span", { className: "text-sm text-muted-foreground truncate max-w-xs", children: topic })] }), _jsxs("div", { className: "flex items-center gap-1 text-muted-foreground", children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { className: "cursor-pointer p-1.5 rounded-md hover:bg-accent hover:text-foreground transition-colors duration-150", type: "button", children: _jsx(Bell, { className: "w-5 h-5" }) }) }), _jsx(TooltipContent, { children: "Notifications" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { className: "cursor-pointer p-1.5 rounded-md hover:bg-accent hover:text-foreground transition-colors duration-150", type: "button", children: _jsx(Pin, { className: "w-5 h-5" }) }) }), _jsx(TooltipContent, { children: "Pins" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { className: "cursor-pointer p-1.5 rounded-md hover:bg-accent hover:text-foreground transition-colors duration-150", type: "button", children: _jsx(UserPlus, { className: "w-5 h-5" }) }) }), _jsx(TooltipContent, { children: "Invite" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { className: `cursor-pointer p-1.5 rounded-md hover:bg-accent transition-colors duration-150 ${showMembers
                                        ? 'text-foreground'
                                        : 'text-muted-foreground hover:text-foreground'}`, type: "button", onClick: onToggleMembers, "aria-pressed": showMembers, children: _jsx(Users, { className: "w-5 h-5" }) }) }), _jsx(TooltipContent, { children: "Member List" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { className: "cursor-pointer p-1.5 rounded-md hover:bg-accent hover:text-foreground transition-colors duration-150", type: "button", children: _jsx(Search, { className: "w-5 h-5" }) }) }), _jsx(TooltipContent, { children: "Search" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { className: "cursor-pointer p-1.5 rounded-md hover:bg-accent hover:text-foreground transition-colors duration-150", type: "button", children: _jsx(HelpCircle, { className: "w-5 h-5" }) }) }), _jsx(TooltipContent, { children: "Help" })] })] })] }));
};
//# sourceMappingURL=ChannelHeader.js.map