import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import { useChannels } from '../hooks/useChannels';
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuTrigger, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger, Tooltip, TooltipContent, TooltipTrigger, } from '@goportal/ui';
import { Plus, Hash, Volume2, ChevronDown, UserPlus, Settings, Mic, Headphones, Bell, Users, LogOut, Zap, } from 'lucide-react';
const sectionLabelClassName = 'text-[11px] uppercase tracking-[0.04em] font-semibold text-muted-foreground/70 whitespace-nowrap';
const SectionHeader = ({ name, expanded, onToggle, onCreateChannel, className = 'mt-4' }) => (_jsxs("div", { className: `flex items-center gap-2 ${className} mb-0.5 px-2 group`, children: [_jsxs("button", { type: "button", onClick: onToggle, className: "flex min-w-0 flex-1 items-center gap-1.5 text-left", children: [_jsx(ChevronDown, { className: `h-3 w-3 flex-shrink-0 text-muted-foreground/70 transition-transform ${!expanded ? '-rotate-90' : ''}` }), _jsx("span", { className: sectionLabelClassName, children: name })] }), _jsx("div", { className: "h-px flex-1 bg-muted-foreground/20" }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { onClick: onCreateChannel, className: "flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-sm text-muted-foreground/60 opacity-0 transition-opacity hover:text-foreground group-hover:opacity-100", type: "button", children: _jsx(Plus, { className: "h-3.5 w-3.5" }) }) }), _jsx(TooltipContent, { children: "Add Channel" })] })] }));
const ChannelRow = ({ channel, active, onSelect }) => {
    const unreadCount = typeof channel.unread === 'number' ? channel.unread : 0;
    const hasUnread = unreadCount > 0;
    const isVoice = channel.type === 'voice';
    const Icon = isVoice ? Volume2 : Hash;
    const rowClassName = active
        ? 'bg-[hsl(240,5%,17%)] text-[hsl(0,0%,96%)]'
        : hasUnread
            ? 'text-[hsl(0,0%,82%)] hover:bg-[hsl(240,5%,17%)] hover:text-[hsl(0,0%,82%)]'
            : 'text-[hsl(0,0%,55%)] hover:bg-[hsl(240,5%,17%)] hover:text-[hsl(0,0%,82%)]';
    const iconClassName = active
        ? 'text-[hsl(0,0%,82%)]'
        : hasUnread
            ? 'text-[hsl(0,0%,72%)] group-hover:text-[hsl(0,0%,82%)]'
            : 'text-[hsl(0,0%,55%)] group-hover:text-[hsl(0,0%,82%)]';
    return (_jsxs("div", { className: "relative overflow-visible", children: [hasUnread && _jsx("span", { className: "absolute -left-1 top-1/2 h-2 w-[3px] -translate-y-1/2 rounded-r-full bg-white" }), _jsxs("button", { onClick: onSelect, className: `group relative flex w-full min-w-0 items-center gap-2 rounded-md px-2 py-[5px] text-left text-[14px] font-normal leading-5 transition-colors ${rowClassName}`, type: "button", children: [_jsxs("div", { className: "flex min-w-0 flex-1 items-center gap-1", children: [_jsx(Icon, { className: `h-4 w-4 flex-shrink-0 ${iconClassName}` }), _jsx("span", { className: "min-w-0 truncate", children: channel.name })] }), _jsxs("div", { className: "relative flex h-[18px] w-[46px] flex-shrink-0 items-center justify-end", children: [!isVoice && hasUnread && (_jsx("span", { className: "inline-flex h-[18px] min-w-[20px] items-center justify-center rounded-[9px] bg-[#f23f43] px-1.5 text-[11px] font-semibold leading-none text-white transition-opacity group-hover:opacity-0", children: unreadCount })), _jsxs("div", { className: "absolute inset-0 flex items-center justify-end gap-0.5 opacity-0 transition-opacity group-hover:opacity-100", children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("span", { className: "flex h-6 w-6 cursor-pointer items-center justify-center rounded-sm text-[hsl(0,0%,70%)] transition-colors hover:bg-black/15 hover:text-[hsl(0,0%,96%)]", children: _jsx(UserPlus, { className: "h-[14px] w-[14px]" }) }) }), _jsx(TooltipContent, { children: "Invite" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("span", { className: "flex h-6 w-6 cursor-pointer items-center justify-center rounded-sm text-[hsl(0,0%,70%)] transition-colors hover:bg-black/15 hover:text-[hsl(0,0%,96%)]", children: _jsx(Settings, { className: "h-[14px] w-[14px]" }) }) }), _jsx(TooltipContent, { children: "Settings" })] })] })] })] }, channel.id)] }));
};
const VoiceActivityRow = ({ channel }) => {
    if (channel.type !== 'voice' || !channel.activeMembers?.length)
        return null;
    return (_jsxs("div", { className: "mb-0.5 ml-[22px]", children: [_jsxs("div", { className: "flex items-center gap-1.5 px-2 py-[3px]", children: [channel.liveLabel && (_jsx("span", { className: "min-w-0 flex-1 truncate text-[11px] text-muted-foreground/70", children: channel.liveLabel })), channel.isLive && (_jsx("span", { className: "flex-shrink-0 rounded-sm bg-red-500 px-1.5 py-[2px] text-[10px] font-bold leading-none tracking-wide text-white", children: "TRUC TIEP" }))] }), _jsx("div", { className: "flex items-center gap-1 px-2 py-[2px]", children: _jsxs("div", { className: "flex items-center", children: [channel.activeMembers.slice(0, 4).map((member, index) => (_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("div", { className: `flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full text-[9px] font-bold text-white ring-[1.5px] ring-[hsl(240,6%,10%)] ${member.color} ${index > 0 ? '-ml-1.5' : ''}`, children: member.avatarUrl ? (_jsx("img", { src: member.avatarUrl, alt: member.name ?? member.initials, className: "h-full w-full rounded-full object-cover" })) : (member.initials) }) }), _jsx(TooltipContent, { children: member.name ?? member.initials })] }, member.id))), channel.activeMembers.length > 4 && (_jsxs("div", { className: "flex h-5 w-5 -ml-1.5 items-center justify-center rounded-full bg-[hsl(240,4%,22%)] text-[9px] font-semibold text-muted-foreground ring-[1.5px] ring-[hsl(240,6%,10%)]", children: ["+", channel.activeMembers.length - 4] }))] }) })] }));
};
/**
 * ChannelSidebar - 240px wide sidebar showing channels for a server
 */
export const ChannelSidebar = ({ serverId = 'default', serverName = 'Server', serverInitials, serverColor = 'bg-indigo-500', serverBannerUrl, serverIconUrl, serverBoostLevel, categories, activeChannelId, onSelectChannel = () => { }, onCreateChannel = () => { }, onInviteMember = () => { }, }) => {
    const { data: channels = [] } = useChannels(serverId);
    const [expandedText, setExpandedText] = useState(true);
    const [expandedVoice, setExpandedVoice] = useState(true);
    const [expandedCategories, setExpandedCategories] = useState({});
    const fromCategories = Array.isArray(categories) && categories.length > 0;
    const textChannels = fromCategories
        ? categories.flatMap((c) => c.channels.filter((ch) => ch.type === 'text'))
        : channels.filter((c) => c.type === 'TEXT');
    const voiceChannels = fromCategories
        ? categories.flatMap((c) => c.channels.filter((ch) => ch.type === 'voice'))
        : channels.filter((c) => c.type === 'VOICE');
    const toggleCategory = (id) => {
        setExpandedCategories((prev) => ({ ...prev, [id]: !(prev[id] ?? true) }));
    };
    const initials = (serverInitials ?? serverName)
        .split(' ')
        .slice(0, 2)
        .map((w) => w[0]?.toUpperCase())
        .join('')
        .slice(0, 2);
    return (_jsxs("aside", { className: "flex h-full w-full flex-col overflow-hidden border-r border-white/5 bg-[hsl(240,6%,10%)]", children: [_jsxs(DropdownMenu, { children: [serverBannerUrl ? (_jsx("div", { className: "flex-shrink-0 border-b border-[hsl(240,4%,13%)]", children: _jsx(DropdownMenuTrigger, { asChild: true, children: _jsxs("button", { type: "button", className: "group relative w-full cursor-pointer overflow-hidden text-left", style: { height: '110px' }, children: [_jsx("div", { className: "absolute inset-0 bg-cover bg-center", style: { backgroundImage: `url(${serverBannerUrl})` } }), _jsx("div", { className: "absolute inset-0 backdrop-blur-[1px]" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/75 via-black/30 to-transparent" }), _jsx("div", { className: "absolute inset-0 bg-black/0 transition-colors duration-150 group-hover:bg-black/20" }), _jsx("div", { className: "absolute right-2 top-2 z-20", children: _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("span", { role: "button", tabIndex: 0, onClick: (e) => {
                                                            e.stopPropagation();
                                                            onInviteMember();
                                                        }, onKeyDown: (e) => {
                                                            if (e.key === 'Enter' || e.key === ' ') {
                                                                e.preventDefault();
                                                                e.stopPropagation();
                                                                onInviteMember();
                                                            }
                                                        }, className: "rounded-md bg-black/30 p-1.5 text-white/70 transition-colors hover:bg-black/50 hover:text-white", children: _jsx(UserPlus, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Invite People" })] }) }), _jsxs("div", { className: "absolute bottom-0 left-0 right-0 z-10 flex items-center gap-2 px-3 pb-2.5 pt-1", children: [serverIconUrl ? (_jsx("img", { src: serverIconUrl, alt: serverName, className: "h-8 w-8 flex-shrink-0 rounded-full object-cover ring-2 ring-black/30" })) : (_jsx("div", { className: `flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full ${serverColor} text-sm font-bold text-white ring-2 ring-black/30`, children: initials })), _jsx("span", { className: "min-w-0 flex-1 truncate text-left text-[15px] font-semibold text-white drop-shadow-md", children: serverName }), typeof serverBoostLevel === 'number' && serverBoostLevel > 0 && (_jsxs("span", { className: "flex flex-shrink-0 items-center gap-1 rounded-full bg-indigo-500/80 px-1.5 py-0.5 text-[10px] font-semibold text-white", children: [_jsx(Zap, { className: "h-2.5 w-2.5" }), "BOOST ", serverBoostLevel] })), _jsx(ChevronDown, { className: "h-4 w-4 flex-shrink-0 text-white/80 drop-shadow-md" })] })] }) }) })) : (_jsx(DropdownMenuTrigger, { asChild: true, children: _jsxs("button", { type: "button", className: "flex h-12 w-full items-center gap-3 border-b border-[hsl(240,4%,13%)] px-3 transition-colors hover:bg-white/[0.03]", children: [_jsx("div", { className: `flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg ${serverColor} text-sm font-bold text-white`, children: initials }), _jsx("span", { className: "flex-1 truncate text-left text-[15px] font-semibold text-[hsl(0,0%,96%)]", children: serverName }), _jsx(ChevronDown, { className: "h-4 w-4 flex-shrink-0 text-[hsl(0,0%,72%)]" })] }) })), _jsxs(DropdownMenuContent, { className: "w-56", align: "start", side: "bottom", children: [_jsxs(DropdownMenuItem, { children: [_jsx(UserPlus, { className: "mr-2 h-4 w-4" }), " Invite People"] }), _jsxs(DropdownMenuItem, { children: [_jsx(Settings, { className: "mr-2 h-4 w-4" }), " Server Settings"] }), _jsxs(DropdownMenuItem, { children: [_jsx(Users, { className: "mr-2 h-4 w-4" }), " Members"] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { children: [_jsx(Bell, { className: "mr-2 h-4 w-4" }), " Notifications"] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { className: "text-red-400 focus:bg-red-500/10 focus:text-red-400", children: [_jsx(LogOut, { className: "mr-2 h-4 w-4" }), " Leave Server"] })] })] }), _jsxs("div", { className: "flex-1 overflow-y-auto px-2 py-2 scrollbar-thin scrollbar-thumb-zinc-700 scrollbar-track-transparent", children: [fromCategories && (_jsx("div", { className: "space-y-0.5", children: categories.map((cat, index) => {
                            const isExpanded = expandedCategories[cat.id] ?? true;
                            return (_jsxs("div", { children: [_jsx(SectionHeader, { name: cat.name, expanded: isExpanded, onToggle: () => toggleCategory(cat.id), onCreateChannel: onCreateChannel, className: index === 0 ? 'mt-0' : 'mt-4' }), isExpanded && (_jsx("div", { className: "space-y-0.5", children: cat.channels.map((ch) => (_jsxs(React.Fragment, { children: [_jsx(ChannelRow, { channel: ch, active: ch.id === activeChannelId, onSelect: () => onSelectChannel(ch.id) }), ch.type === 'voice' && _jsx(VoiceActivityRow, { channel: ch })] }, ch.id))) }))] }, cat.id));
                        }) })), !fromCategories && textChannels.length > 0 && (_jsxs("div", { children: [_jsx(SectionHeader, { name: "Text Channels", expanded: expandedText, onToggle: () => setExpandedText(!expandedText), onCreateChannel: onCreateChannel, className: "mt-0" }), expandedText && (_jsx("div", { className: "space-y-0.5", children: textChannels.map((channel) => (_jsx(ChannelRow, { channel: {
                                        id: channel.id,
                                        name: channel.name,
                                        type: 'text',
                                        unread: channel?.unreadCount ?? channel?.unread_count,
                                    }, active: channel.id === activeChannelId, onSelect: () => onSelectChannel(channel.id) }, channel.id))) }))] })), !fromCategories && voiceChannels.length > 0 && (_jsxs("div", { children: [_jsx(SectionHeader, { name: "Voice Channels", expanded: expandedVoice, onToggle: () => setExpandedVoice(!expandedVoice), onCreateChannel: onCreateChannel }), expandedVoice && (_jsx("div", { className: "space-y-0.5", children: voiceChannels.map((channel) => (_jsxs(React.Fragment, { children: [_jsx(ChannelRow, { channel: {
                                                id: channel.id,
                                                name: channel.name,
                                                type: 'voice',
                                                unread: channel?.unreadCount ?? channel?.unread_count,
                                                activeMembers: channel?.activeMembers,
                                                liveLabel: channel?.liveLabel,
                                                isLive: channel?.isLive,
                                            }, active: channel.id === activeChannelId, onSelect: () => onSelectChannel(channel.id) }), _jsx(VoiceActivityRow, { channel: {
                                                id: channel.id,
                                                name: channel.name,
                                                type: 'voice',
                                                unread: channel?.unreadCount ?? channel?.unread_count,
                                                activeMembers: channel?.activeMembers,
                                                liveLabel: channel?.liveLabel,
                                                isLive: channel?.isLive,
                                            } })] }, channel.id))) }))] }))] }), _jsxs("div", { className: "flex h-[52px] items-center justify-between bg-[hsl(240,7%,7%)] px-2", children: [_jsxs(ContextMenu, { children: [_jsx(ContextMenuTrigger, { asChild: true, children: _jsxs("button", { type: "button", className: "flex min-w-0 items-center gap-2 rounded-md px-1.5 py-1 transition-colors hover:bg-white/[0.06]", children: [_jsxs("div", { className: "relative h-8 w-8 flex-shrink-0", children: [_jsx("div", { className: "flex h-8 w-8 items-center justify-center rounded-full bg-accent", children: _jsx("span", { className: "text-xs font-bold text-accent-foreground", children: "Y" }) }), _jsx("span", { className: "absolute bottom-0 right-0 h-[10px] w-[10px] rounded-full border-2 border-[hsl(240,7%,7%)] bg-[#23a55a]" })] }), _jsxs("div", { className: "min-w-0 text-left", children: [_jsx("p", { className: "truncate text-[13px] font-semibold leading-4 text-[hsl(0,0%,96%)]", children: "You" }), _jsx("p", { className: "truncate text-[11px] leading-3 text-[hsl(0,0%,60%)]", children: "Online" })] })] }) }), _jsx(ContextMenuContent, { className: "w-40", children: _jsx(ContextMenuItem, { children: "Log out" }) })] }), _jsxs("div", { className: "flex items-center gap-0.5", children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { type: "button", className: "flex h-8 w-8 items-center justify-center rounded-md text-[hsl(0,0%,70%)] transition-colors hover:bg-white/[0.06] hover:text-[hsl(0,0%,96%)]", children: _jsx(Mic, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Mic" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { type: "button", className: "flex h-8 w-8 items-center justify-center rounded-md text-[hsl(0,0%,70%)] transition-colors hover:bg-white/[0.06] hover:text-[hsl(0,0%,96%)]", children: _jsx(Headphones, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Headphones" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("button", { type: "button", className: "flex h-8 w-8 items-center justify-center rounded-md text-[hsl(0,0%,70%)] transition-colors hover:bg-white/[0.06] hover:text-[hsl(0,0%,96%)]", children: _jsx(Settings, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Settings" })] })] })] })] }));
};
//# sourceMappingURL=ChannelSidebar.js.map